[colors.bright]
black = "#9e9778"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4008f"
red = "#f4005f"
white = "#f6f6ef"
yellow = "#e0d561"

[colors.normal]
black = "#1a1a1a"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4008f"
red = "#f4005f"
white = "#c4c5b5"
yellow = "#fa8419"

[colors.primary]
background = "#1E1D23"
foreground = "#F0F0F0"
